#platforms/windows/core-ffi/Cargo.toml
[package]
name = "core-ffi-windows"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
cb_core = { path = "../../../cb_core" }
