#platforms/windows/core-ffi/Cargo.toml
[package]
name = "core-ffi-windows"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
cb_core = { path = "../../../cb_core" }
once_cell = "1.21.3"

